x-logging: &base-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"
services:
  workspace:
    init: true
    build:
      context: ./dockerfiles/app
      target: workspace
      args:
        - USER_NAME=${USER_NAME:-dev}
        - USER_UID=${COMPOSE_USER_UID:-1000}
        - USER_GID=${COMPOSE_USER_GID:-1000}
    volumes:
      - output:/mnt
      - history:/usr/local/history
      - vscext:/home/dev/.vscode-server/extensions
      - gobuildcache:/home/dev/.cache/go-build
      - gomodcache:/go/pkg/mod
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    logging: *base-logging
volumes:
  vscext:
  history:
  gobuildcache:
  gomodcache: